# enum for id layer, when it's used update num_layers
int8 ALL_LAYERS=-1

# enum for task type
int8 PLAN=1
int8 EXECUTE=2

# Request
uint8 id_pick_pallet
uint8 id_place_pallet
int8 id_pick_layer
int8 id_place_layer
int8 num_layers 1
int8 task_type
---
# Result
bool success
string error_log
uint8 id_pallet_failed
uint8 id_layer_failed
uint8 id_box_failed
---
# Feedback
string log
