---
# Define the result that will be published after the action execution ends.
bool success
string error_log
uint8 box_id_failed
---
# Define a feedback message that will be published during action execution.
uint8 box_id
string log
