name: Build and Package ROS 2 PKG

on:
  push:
    branches:
      - humble
  pull_request:
    branches:
      - humble

jobs:
  build_and_package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: InnoboticsSRL/awtube_interfaces

    - name: Setup ROS humble
      uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: humble

    - name: Set up ROS workspace
      run: |
        mkdir -p ~/ros_ws/src
        cp -r . ~/ros_ws/src/
        cd ~/ros_ws

    - name: Compile package
      run: |
        cd ~/ros_ws
        colcon build --packages-select ${{ github.event.repository.name }} --symlink-install
      env:
        TARGET_ROS2_DISTRO: humble

    # Step to generate the Debian package (.deb)
    - name: Generate Debian package
      run: |
        cd ~/ros_ws/install
        mkdir -p DEBIAN
        echo "Package: ${{ github.event.repository.name }}" > DEBIAN/control
        echo "Version: 1.0" >> DEBIAN/control
        echo "Section: misc" >> DEBIAN/control
        echo "Priority: optional" >> DEBIAN/control
        echo "Architecture: all" >> DEBIAN/control
        echo "Maintainer: Your Name <your.email@example.com>" >> DEBIAN/control
        echo "Description: ROS 2 package ${{ github.event.repository.name }}" >> DEBIAN/control
        dpkg-deb --build ~/ros_ws/install ~/ros_ws/${{ github.event.repository.name }}.deb

    # Upload the generated .deb file as an artifact
    - name: Upload Debian package
      uses: actions/upload-artifact@v3
      with:
        name: debian-package
        path: ~/ros_ws/${{ github.event.repository.name }}.deb
