name: Build and Package ROS 2 PKG

on:
  push:
    branches:
      - humble
  pull_request:
    branches:
      - humble

jobs:
  build_and_package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: InnoboticsSRL/awtube_interfaces

    - name: Setup ROS humble
      uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: humble

    - uses: ros-tooling/action-ros-ci@v0.3
      with:
        package-name: awtube_interfaces
        target-ros2-distro: humble

    - name: Build Debian packages
      uses: ichiro-its/ros2-build-debian-action@main
      with:
        ros2-distro: rolling

    - name: Upload Debian package
      uses: actions/upload-artifact@v3
      with:
        name: debian-package
        path:  dist/awtube_interfaces.deb
