name: Build and Package ROS 2 PKG

on:
  push:
    branches:
      - humble
  pull_request:
    branches:
      - humble

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Containerized Build
        uses: ./.ci/build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debian_package
          path: /ws/src/*.deb
