name: Build and Package ROS 2 PKG

on:
  push:
    branches:
      - humble
  pull_request:
    branches:
      - humble

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup ROS 2
        run: |
          docker pull ros:humble-ros-base
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ros:humble-ros-base bash -c "
          apt-get update && \
          apt-get install -y python3-colcon-common-extensions && \
          apt-get install -y python3-pip && \
          pip3 install -U setuptools
          "

      - name: Install dependencies
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ros:humble-ros-base bash -c "
          apt-get update && \
          rosdep update && \
          rosdep install -y --from-paths src --ignore-src --rosdistro humble
          "

      - name: Build the package
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ros:humble-ros-base bash -c "
          source /opt/ros/humble/setup.bash && \
          colcon build --symlink-install
          "

      - name: Create Debian package
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ros:humble-ros-base bash -c "
          source /opt/ros/humble/setup.bash && \
          cd build/your_package_name && \
          ament debian --create-package
          "

      - name: Upload Debian package
        uses: actions/upload-artifact@v3
        with:
          name: debian-packages
          path: |
            build/your_package_name/*.deb
